### ISSUE TITLE
Command unregister <node-id>

### ISSUE THREAD

**Issue by herry13** [fruit-testbed/fruit-cli#4]
When a node is handed over to a different owner, then the current owner should unregister the node from his/her group so that it can be registered to the new owner.

Command `unregister <node-id>` performs the node unregistration process by sending the request to the API server.

**Comment by tonyg** [comment]
As of v0.5.0 (and associated server-side changes) this is implemented as `fruit-cli node reset`:

```
usage: fruit-cli node reset [-h] node

Deletes all records associated with a specific node.

positional arguments:
  node        Specify the ID of the node to reset

optional arguments:
  -h, --help  show this help message and exit
```
